django_project/chat/urls.py
from django.conf.urls import patterns, url

__author__ = 'nonameitem'

urlpatterns = patterns('',
                       url(r'^$', 'chat.views.show_chat_list', name='main'),
                       url(r'^new/$', 'chat.views.create_chat', name='new'),
                       url(r'^(?P<chat_id>\d+)/$', 'chat.views.show_chat', name='chat'),
                       url(r'^post/(?P<chat_id>\d+)/$', 'chat.views.post', name='post'),
                       url(r'^add_user/(?P<chat_id>\d+)/$', 'chat.views.add_user', name='add_user'),
                       url(r'^add_users/(?P<chat_id>\d+)/$', 'chat.views.add_users', name='add_users'),
                       url(r'^leave/(?P<chat_id>\d+)/$', 'chat.views.leave', name='leave'),
                       url(r'^change_topic/', 'chat.views.change_topic', name='change_topic'),
                       url(r'^get_previous/(?P<chat_id>\d+)/$', 'chat.views.get_previous', name='previous'),
                       url(r'^get_updates/(?P<chat_id>\d+)/$', 'chat.views.get_updates', name='updates'),
                       url(r'^merge_private/(?P<user_id>\d+)/$', 'chat.views.merge_private', name='merge_private'),
                       )

django_project/django_project/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
import django_project.settings as settings
import django_project.views as views

urlpatterns = patterns('',
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^accounts/register/$', views.MyRegistrationView.as_view(), name='registration_register'),
                       url(r'^accounts/profile/$', 'django_project.views.my_profile', name='my_profile'),

                       url(r'^accounts/', include('registration.backends.simple.urls')),
                       url(r'^chat/', include('chat.urls', namespace='chat')),
                       url(r'^snippetalk/', include('snippetalk.urls', namespace='snippetalk')),
                       url(r'^ca/', include('cell_auto.urls', namespace='ca')),
                       url(r'^bot/', include('bots_common.urls')),

                       url(r'^$', 'django_project.views.home', name='home'),
                       url(r'^user/(?P<username>\w+)/$', views.profile, name='profile'),
                       url(r'^change_photo/(?P<user_id>\d+)/$', views.change_photo, name='change_photo'),
                       url(r'^change_profile/(?P<user_id>\d+)/$', views.change_profile, name='change_profile'),
                       )

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_project/django_project/models.py
import datetime
import os
from django.contrib.auth.models import User
from django.db import models
from django.db.models.fields.related import OneToOneField

from django_project.fields import ThumbnailImageField


class UserProfile(models.Model):
    user = OneToOneField(User)

    SEX_CHOICES = (
        (0, "Female"),
        (1, "Male"),
        (2, "Undefined")
    )

    sex = models.IntegerField(choices=SEX_CHOICES, default=2)
    profile_image = ThumbnailImageField(upload_to='images/', null=True)
    about = models.TextField(blank=True)

    def set_profile_image(self, f):
        filename = str(datetime.datetime.now()) + "-" + self.user.username + '.' + f.name.split('.')[-1]
        self.profile_image.delete()
        self.profile_image.save(filename, f)
        self.save()

    @property
    def image_url(self):
        return self.profile_image.thumb_url if self.profile_image else "/media/images/default.jpg"

    def __str__(self):
        return self.user.username

django_project/django_project/forms.py
from django import forms
from django.contrib.auth.models import User
from django_project.models import UserProfile

__author__ = 'nonameitem'


class UserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name')


class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ('sex', 'about')


class ImageUploadForm(forms.Form):
    image = forms.ImageField()

django_project/django_project/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.exceptions import PermissionDenied
from django.core.urlresolvers import reverse
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from registration.backends.simple.views import RegistrationView

from django_project.models import UserProfile
from django_project.forms import ImageUploadForm, UserForm, UserProfileForm
from chat.models import Chat
from chat.forms import PrivateChatForm
from chat.utils import get_private_chats, get_chats_without_user


class MyRegistrationView(RegistrationView):
    def get_success_url(self, request, user):
        return '/user/{0}'.format(user.username)

    def register(self, request, form):
        new_user = super().register(request, form)
        new_profile = UserProfile()
        new_profile.user = new_user
        new_profile.save()
        return new_user


def home(request):
    return render_to_response('django_project/home.html', RequestContext(request))


def profile(request, username):
    private_chats = None
    chats_without_user = None
    private_chat_form = None
    open_new_chat_form = False
    context = RequestContext(request)

    logged_user = request.user
    user = get_object_or_404(User, username=username)
    user_profile = UserProfile.objects.filter(user=user)[0]

    if request.user != user:
        chats_without_user = get_chats_without_user(request.user, user)

        private_chats = get_private_chats(request.user, user)
        if request.method != 'POST':
            new_private_chat = Chat()
            new_private_chat.name = "{0} <-> {1}".format(request.user.username, user.username)
            private_chat_form = PrivateChatForm(instance=new_private_chat)
        else:
            private_chat_form = PrivateChatForm(request.POST)
            if private_chat_form.is_valid():
                new_private_chat = private_chat_form.save()
                new_private_chat.participants.add(request.user)
                new_private_chat.participants.add(user)
                new_private_chat.save()
                return HttpResponseRedirect(reverse('chat:chat', kwargs={'chat_id': new_private_chat.id}))
            else:
                open_new_chat_form = True

    return render_to_response("django_project/profile.html",
                              {"self": logged_user == user,
                               "get_user": user,
                               "user_profile": user_profile,
                               "private_chats": private_chats,
                               "private_chat_form": private_chat_form,
                               "open_new_chat_form": open_new_chat_form,
                               "chats_without_user": chats_without_user},
                              context)


@login_required
def change_photo(request, user_id):
    try:
        user = User.objects.get(id=user_id)
    except User.DoesNotExist:
        raise Http404
    logged_user = request.user
    if logged_user != user:
        raise PermissionDenied
    if request.method == 'POST':
        form = ImageUploadForm(request.POST, request.FILES)
        if form.is_valid():
            user_profile = user.userprofile
            user_profile.set_profile_image(request.FILES['image'])
    return HttpResponseRedirect(reverse('profile', kwargs={'username': user.username}))


def change_profile(request, user_id):
    try:
        user = User.objects.get(id=user_id)
    except User.DoesNotExist:
        raise Http404
    logged_user = request.user
    if logged_user != user:
        raise PermissionDenied
    user_profile = UserProfile.objects.filter(user=user)[0]

    if request.method == 'POST':
        user_form = UserForm(request.POST)
        user_profile_form = UserProfileForm(request.POST)
        if user_form.is_valid() and user_profile_form.is_valid():
            user.first_name = user_form.cleaned_data['first_name']
            user.last_name = user_form.cleaned_data['last_name']
            user.email = user_form.cleaned_data['email']
            user.save()
            user_profile.sex = user_profile_form.cleaned_data['sex']
            user_profile.about = user_profile_form.cleaned_data['about']
            user_profile.save()
            return HttpResponseRedirect(reverse('profile', kwargs={'username': user.username}))
    else:
        user_form = UserForm()
        user_profile_form = UserProfileForm()
    return render_to_response('django_project/change_profile.html',
                              {'get_user': user,
                               'user_profile': user_profile,
                               'user_form': user_form,
                               'profile_form': user_profile_form},
                              RequestContext(request))


@login_required
def my_profile(request):
    return HttpResponseRedirect(reverse('profile', kwargs={'username': request.user.username}))

django_project/django_project/templates/django_project/base.html
<!doctype html>
{% load staticfiles %}

<html>
    <head lang="en">
        <meta charset="UTF-8">
        <title>Sandbox: {% block title %}{% endblock %}</title>
        <link href="{% static "bootstrap/css/bootstrap.min.css" %}" rel="stylesheet" type="text/css">
        <link href="{% static "bootstrap/css/bootstrap-theme.css" %}" rel="stylesheet" type="text/css">
        {% block headers %}{% endblock %}
    </head>
    <body>
    <nav class="navbar navbar-default" role="navigation">
    	<!-- Brand and toggle get grouped for better mobile display -->
    	<div class="navbar-header">
    		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
    			<span class="sr-only">Toggle navigation</span>
    			<span class="icon-bar"></span>
    			<span class="icon-bar"></span>
    			<span class="icon-bar"></span>
    		</button>
    		<a class="navbar-brand" href="#">Home</a>
    	</div>
    
    	<!-- Collect the nav links, forms, and other content for toggling -->
    	<div class="collapse navbar-collapse navbar-ex1-collapse">
    		<ul class="nav navbar-nav">
                <li class="dropdown">
    				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Projects <b class="caret"></b></a>
    				<ul class="dropdown-menu">
    					<li><a href="#">Action</a></li>
    					<li><a href="#">Another action</a></li>
    					<li><a href="#">Something else here</a></li>
    					<li><a href="#">Separated link</a></li>
    				</ul>
    			</li>
    		</ul>

    		<ul class="nav navbar-nav navbar-right">
    			{% if user.is_authenticated %}
                    <li><a href="/user/{{ user.id }}">Profile</a></li>
                    <li><a href="/logout">Log Out</a></li>
                    {% else %}
                    <li><a href="/login/">Log In</a></li>
                    <li><a href="/register/">Register</a></li>
                {% endif %}
    		</ul>
    	</div><!-- /.navbar-collapse -->
    </nav>
    {% block content %}{% endblock %}
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static "bootstrap/js/bootstrap.js" %}"></script>
    </body>
</html>

django_project/django_project/templates/django_project/change_profile.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
    change your profile
{% endblock %}

{% block headers %}
    <link href="{% static "django_project/css/auth-form.css" %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <form class="form-signin" action="#" method="post" role="form">
        {% csrf_token %}
    	<legend class="h4">Update your profile info</legend>

    	<div class="form-group">
            {% if user_form.first_name.errors %}
            <div class="alert alert-danger" role="alert">
                <label for="id_first_name">{{ user_form.first_name.errors.as_text }}</label>
            </div>
            {% endif %}
    		<label for="id_first_name">First name</label>
    		<input type="text" class="form-control" name="first_name" id="id_first_name" value="{{ get_user.first_name }}">
    	</div>

        <div class="form-group">
            {% if user_form.last_name.errors %}
            <div class="alert alert-danger" role="alert">
                <label for="id_last_name">{{ user_form.last_name.errors.as_text }}</label>
            </div>
            {% endif %}
    		<label for="id_last_name">Last name</label>
    		<input type="text" class="form-control" name="last_name" id="id_last_name" value="{{ get_user.last_name }}">
    	</div>

        <div class="form-group">
            {% if user_form.email.errors %}
            <div class="alert alert-danger" role="alert">
                <label for="id_email">{{ user_form.email.errors.as_text }}</label>
            </div>
            {% endif %}
    		<label for="id_email">Email</label>
    		<input type="text" class="form-control" name="email" id="id_email" value="{{ get_user.email }}">
    	</div>

        <div class="form-group">
            {% if profile_form.sex.errors %}
            <div class="alert alert-danger" role="alert">
                <label for="id_sex">{{ user_profile_form.sex.errors.as_text }}</label>
            </div>
            {% endif %}
            <label for="id_sex">Sex</label>
            <select class="form-control" id="id_sex" name="sex">
                <option value="0" {% if user_profile.sex == 0 %}selected="selected"{% endif %}>Female</option>
                <option value="1" {% if user_profile.sex == 1 %}selected="selected"{% endif %}>Male</option>
                <option value="2" {% if user_profile.sex == 2 %}selected="selected"{% endif %}>Undefined</option>
            </select>
        </div>

        <div class="form-group">
            {% if profile_form.about.errors %}
            <div class="alert alert-danger" role="alert">
                <label for="id_about">{{ user_profile_form.about.errors.as_text }}</label>
            </div>
            {% endif %}
    		<label for="id_about">About</label>
            <textarea class="form-control" name="about" id="id_about">{{ user_profile.about }}</textarea>
    	</div>


    	<button type="submit" class="btn btn-default btn-lg btn-block">Submit</button>
    </form>
{% endblock %}

{% block scripts %}
  <script src="{% static "select2/js/select2.min.js" %}"></script>
  <script >
    $('#id_sex').select2();
  </script>
{% endblock %}

django_project/django_project/templates/django_project/home.html
{% extends "base.html" %}

{% block title %}
    main page
{% endblock %}

{% block content %}
   <div class="jumbotron">
   		<h2>Welcome to my sandbox</h2>
   		<p align="justify">This is projects, I wrote while learn python, django, tornado, etc. Some of them can require you to
        register. Feel free to play with them and if you find any bugs please tell me about it via email (nonameitem@me.com)</p>
   		<h2>
   			List of project:
   		</h2>
        {% if projects %}
            <ul>
            {% for project in projects %}
                 <p><li><a href="{{ project.0 }}"><strong>{{ project.1 }}</strong>: {{ project.2 }}</a></li></p>
            {% endfor %}
            </ul>
        {% else %}
            <p>There are no projects, sorry</p>
        {% endif %}
   	</div>
{% endblock %}

django_project/django_project/templates/django_project/profile.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}
  {% if self %}
    your profile
  {% else %}
    {{ get_user.username }}'s profile
  {% endif %}
{% endblock %}

{% block headers %}
  <link href="{% static "django_project/css/profile.css" %}" rel="stylesheet">
{% endblock %}

{% block content %}
  <div class="modal fade" id="modal-new-chat">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Create new chat</h4>
        </div>
        <div class="modal-body">
          <form action="#" method="post" role="form" id="new-chat-form">
            {% csrf_token %}
            {{ private_chat_form|crispy }}
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary" id="new-chat-submit">Start new chat</button>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->

  <div class="modal fade" id="image-modal">
  	<div class="modal-dialog modal-lg">
  		<div class="modal-content">
  			<div align="center" class="modal-body">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          {% if user_profile.profile_image %}
            <img  src="{{ user_profile.profile_image.url }}" alt="">
          {% else %}
            <img  src="/media/images/default.jpg" alt="">
          {% endif %}

  			</div>
  		</div><!-- /.modal-content -->
  	</div><!-- /.modal-dialog -->
  </div><!-- /.modal -->

  <div class="page-header">
    <h2>{{ get_user.username }}<small>'s profile</small></h2>
  </div>
  <div class="row">
    <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
    <a data-toggle="modal" href="#image-modal" class="thumbnail">
      {% if user_profile.profile_image %}


          <img src="{{ user_profile.profile_image.thumb_url }}" alt="">

      {% else %}
          <img src="/media/images/default.jpg" alt="A generic square placeholder image with a white border around it, making it resemble a photograph taken with an old instant camera">
      {% endif %}
        </a>

      {% if self %}
        <form action="{% url 'change_photo' get_user.id %}" method="post" class="form-select"
              enctype="multipart/form-data">
          {% csrf_token %}
          <label for="id_image" class="hidden">Image:</label>
          <input type="file" id="id_image" class="hidden" name="image">
          <button class="btn btn-default btn-block" id="change_photo" type="submit">Change photo</button>
        </form>
      {% else %}
        {% if user.is_authenticated %}
          <div class="btn-group-vertical btn-block" role="group">
            <div class=" btn-group btn-block">
              <a id="private-chat" role="button" data-toggle="dropdown" class="btn btn-default btn-block dropdown-toggle" href="#">
                Private chat <span class="caret"></span>
              </a>
              <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu">
                <li>
                  <a role="button" data-toggle="modal" data-target="#modal-new-chat">Start new private chat</a>
                </li>
                <li class="divider"></li>
                {% for private_chat in private_chats %}
                  <li><a href="{% url 'chat:chat' private_chat.id %}" target="_blank">
                    {{ private_chat.name }}
                  </a></li>
                  {% if forloop.last %}
                    <li class="divider"></li>
                    <li><a href="{% url 'chat:merge_private' get_user.id %}">Merge private chats</a></li>
                  {% endif %}
                {% endfor %}
              </ul>
            </div>
            <div class=" btn-group btn-block">
              <a id="invite-button" role="button" data-toggle="dropdown" class="btn btn-default btn-block dropdown-toggle" href="#">
                Add to chat <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                {% for chat in chats_without_user %}
                  <li><a role="button" data-id="{{ chat.id }}" class="add-to-chat">{{ chat.name }}</a></li>
                {% endfor %}
            </div>
          </div>
        {% endif %}
      {% endif %}
    </div>

    <div class="col-xs-9 col-sm-9 col-md-9 col-lg-9">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Info</h3>
        </div>
        <div class="panel-body">
          <ul>
            <li><p><strong>First name:</strong>
              {% if get_user.first_name %}
                {{ get_user.first_name }}
              {% else %}
                Undefined
              {% endif %}
            </p></li>
            <li><p><strong>Last name:</strong>
              {% if get_user.last_name %}
                {{ get_user.last_name }}
              {% else %}
                Undefined
              {% endif %}
            </p></li>
            <li><p><strong>Sex:</strong> {{ user_profile.get_sex_display }}</p></li>
            <li><p><strong>About:</strong> {{ user_profile.about }}</p></li>
          </ul>
          {% if self %}
            <a class="btn btn-default" href="/change_profile/{{ get_user.id }}" role="button">Change profile</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>

{% endblock %}

{% block scripts %}
  <script src="{% static "django_project/js/profile.js" %}"></script>
  <script type="text/javascript">
    $(document).ready(function(){
      userId = {{ get_user.id }};
      {% if open_new_chat_form %}
        $('#modal-new-chat').modal('show');
      {% endif %}
    });
  </script>
{% endblock %}