django_project/chat/urls.py
from django.conf.urls import patterns, url

__author__ = 'nonameitem'

urlpatterns = patterns('',
                       url(r'^$', 'chat.views.show_chat_list', name='main'),
                       url(r'^new/$', 'chat.views.create_chat', name='new'),
                       url(r'^(?P<chat_id>\d+)/$', 'chat.views.show_chat', name='chat'),
                       url(r'^post/(?P<chat_id>\d+)/$', 'chat.views.post', name='post'),
                       url(r'^add_user/(?P<chat_id>\d+)/$', 'chat.views.add_user', name='add_user'),
                       url(r'^add_users/(?P<chat_id>\d+)/$', 'chat.views.add_users', name='add_users'),
                       url(r'^leave/(?P<chat_id>\d+)/$', 'chat.views.leave', name='leave'),
                       url(r'^change_topic/', 'chat.views.change_topic', name='change_topic'),
                       url(r'^get_previous/(?P<chat_id>\d+)/$', 'chat.views.get_previous', name='previous'),
                       url(r'^get_updates/(?P<chat_id>\d+)/$', 'chat.views.get_updates', name='updates'),
                       url(r'^merge_private/(?P<user_id>\d+)/$', 'chat.views.merge_private', name='merge_private'),
                       )

django_project/django_project/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
import django_project.settings as settings
import django_project.views as views

urlpatterns = patterns('',
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^accounts/register/$', views.MyRegistrationView.as_view(), name='registration_register'),
                       url(r'^accounts/profile/$', 'django_project.views.my_profile', name='my_profile'),

                       url(r'^accounts/', include('registration.backends.simple.urls')),
                       url(r'^chat/', include('chat.urls', namespace='chat')),
                       url(r'^snippetalk/', include('snippetalk.urls', namespace='snippetalk')),
                       url(r'^ca/', include('cell_auto.urls', namespace='ca')),
                       url(r'^bot/', include('bots_common.urls')),

                       url(r'^$', 'django_project.views.home', name='home'),
                       url(r'^user/(?P<username>\w+)/$', views.profile, name='profile'),
                       url(r'^change_photo/(?P<user_id>\d+)/$', views.change_photo, name='change_photo'),
                       url(r'^change_profile/(?P<user_id>\d+)/$', views.change_profile, name='change_profile'),
                       )

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_project/snippetalk/urls.py
from django.conf.urls import patterns, url

__author__ = 'nonameitem'

urlpatterns = patterns('',
                       url(r'^$', 'snippetalk.views.recent', name='recent'),
                       url(r'^my/$', 'snippetalk.views.my', name='my'),
                       url(r'^create/$', 'snippetalk.views.show', name='create'),
                       url(r'^(?P<snippet_id>\d+)/$', 'snippetalk.views.show', name='snippet'),
                       url(r'^highlight/$', 'snippetalk.views.get_highlight', name='get_highlight'),
                       url(r'^save/$', 'snippetalk.views.save', name='save'),
                       url(r'^delete/(?P<snippet_id>\d+)/$', 'snippetalk.views.delete', name='delete'),
                       url(r'^fork/(?P<snippet_id>\d+)/$', 'snippetalk.views.show', {'fork': True}, name='fork'),
                       url(r'^comment/$', 'snippetalk.views.comment', name='comment'),
                       url(r'^download/(?P<snippet_id>\d+)/$', 'snippetalk.views.download', name='download'),
                       url(r'^upload/$', 'snippetalk.views.upload', name='upload'),
                       url(r'^preview/$', 'snippetalk.views.preview', name='preview'),
                       )

django_project/snippetalk/models.py
from tempfile import TemporaryFile

from django.contrib.auth.models import User
from django.db import models
from django.template import Template, Context, loader
from django.template.loader import render_to_string

import snippetalk.utils as u


class Snippet(models.Model):
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    public = models.IntegerField(default=1, choices=((1, 'Public'), (2, 'Private')),
                                 verbose_name="Publicity")
    name = models.CharField(max_length=100, default="Untitled")
    description = models.TextField(blank=True)
    language = models.IntegerField(choices=u.LANGUAGE_CHOICES, default=u.PLAIN_TEXT)
    code = models.TextField()

    @property
    def highlighted(self):
        return u.highlight(self.code, self.get_language_display())

    @property
    def modified_str(self):
        t = Template('{{ date }}')
        return t.render(Context({'date': self.modified}))

    @property
    def top_level_comments(self):
        return self.comments.filter(parent__isnull=True)

    def get_file(self):
        filename = u.get_filename(self.name, self.get_language_display())
        f = open(filename, mode='wt')
        f.write(self.code)
        f.close()
        return filename


class Comment(models.Model):
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    created = models.DateTimeField(auto_now_add=True)
    text = models.TextField()
    to_snippet = models.ForeignKey(Snippet, on_delete=models.CASCADE, related_name='comments')
    parent = models.ForeignKey('self', null=True, default=None, related_name='answers')
    snippets = models.ManyToManyField(Snippet, default=None, related_name='mentions')

    def render(self):
        return render_to_string('snippetalk/comment.html', {'comm': self})

django_project/snippetalk/forms.py
from django import forms
from snippetalk.models import Snippet


class SnippetForm(forms.ModelForm):
    class Meta:
        model = Snippet
        fields = ('name', 'public', 'language', 'code', 'description')
        widgets = {
            'public': forms.RadioSelect()
        }


class FileForm(forms.Form):
    file = forms.FileField()

django_project/snippetalk/views.py
import json
import os
import re

from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.shortcuts import render, get_object_or_404

from django.shortcuts import render_to_response
from django.template import RequestContext

from snippetalk.forms import SnippetForm, FileForm
from snippetalk.models import Snippet, Comment
from snippetalk.utils import LANGUAGE_CHOICES, LANG_JS, highlight, PLAIN_TEXT, parse_filename


# url regex from http://daringfireball.net/2010/07/improved_regex_for_matching_urls
URL_REGEX = re.compile(r'''(?i)\b((?:[a-z][\w-]+:(?:/{1,3}|[a-z0-9%])|www\d{0,3}[.]|[a-z0-9.\-]+[.][a-z]{2,4}/)(?:[^\s\
()<>]+|\(([^\s()<>]+|(\([^\s()<>]+\)))*\))+(?:\(([^\s()<>]+|(\([^\s()<>]+\)))*\)|[^\s`!()\[\]{};:'".,<>?«»“”‘’]))''')


def wrap_links(text):
    return URL_REGEX.sub(lambda x: '<a href="{0}">{0}</a>'.format(x.group(0)), text)


# /snippetalk/
def recent(request):
    snippets = Snippet.objects.filter(public=1).order_by('-modified')
    return render_to_response('snippetalk/list.html',
                              {
                                  'active_page': "recent",
                                  'snippets':    snippets,
                                  'title':       "Recent snippets"
                              },
                              RequestContext(request))


# /snippetalk/my/
@login_required
def my(request):
    snippets = Snippet.objects.filter(author=request.user).order_by('-modified')
    return render_to_response('snippetalk/list.html',
                              {
                                  'active_page': "my",
                                  'snippets':    snippets,
                                  'title':       "My snippets"
                              },
                              RequestContext(request))


def create(request):
    if request.method == 'POST':
        form = SnippetForm(request.POST)
        if form.is_valid():
            snippet = form.save()
            user = request.user
            if user.is_authenticated():
                snippet.author = user
                snippet.save()
            return JsonResponse(status=200, data={'link': "/snippetalk/{0}".format(snippet.id)})
        else:
            return JsonResponse(status=400,
                                data={'message': 'Check fields', 'errorlist': form.errors})
    else:
        return JsonResponse(status=400, data={'message': 'Use POST'})


# /snippetalk/create/, /snippetalk/<id>/, /snippetalk/fork/<id>/
def show(request, snippet_id=None, fork=False):
    active_page = None
    my_snippets = None
    if request.user.is_authenticated():
        my_snippets = request.user.snippet_set.filter(public=1).order_by('name')

    try:
        snippet = Snippet.objects.get(id=snippet_id)
        mine = snippet.author == request.user
        title = "{0} by {1}".format(snippet.name, snippet.author.username if snippet.author
                                    else "Anonymous")
        if fork:
            active_page = 'create'
            title = "Fork " + title
            fork = Snippet()
            fork.name = snippet.name + "-fork"
            if request.user.is_authenticated():
                fork.author = request.user
            fork.public = 1
            fork.code = snippet.code
            fork.language = snippet.language
            snippet = fork
            mine = True
    except Snippet.DoesNotExist:
        title = "Create snippet"
        active_page = 'create'
        snippet = None
        mine = True
    return render_to_response('snippetalk/snippet.html',
                              {
                                  'snippet':     snippet,
                                  'mine':        mine,
                                  'langs':       LANG_JS,
                                  'plain_text':  PLAIN_TEXT,
                                  'title':       title,
                                  'active_page': active_page,
                                  'my_snippets': my_snippets
                              },
                              RequestContext(request))


# /snippetalk/highlight/
def get_highlight(request):
    if request.method == 'GET':
        l = int(request.GET['lang']) - 1
        lang_name = LANGUAGE_CHOICES[l][1]
        code = highlight(request.GET['code'], lang_name)
        return JsonResponse(status=200, data={'code': code})
    else:
        return JsonResponse(status=400, data={'message': "Use GET"})


# /snippetalk/save/
def save(request):
    if request.method == 'POST':
        if request.POST['id']:
            try:
                snippet = Snippet.objects.get(id=int(request.POST['id']))
                new = SnippetForm(request.POST)
                if new.is_valid():
                    snippet.name = new.cleaned_data['name']
                    snippet.public = new.cleaned_data['public']
                    snippet.language = new.cleaned_data['language']
                    snippet.code = new.cleaned_data['code']
                    snippet.description = new.cleaned_data['description']
                    snippet.save()
                    return JsonResponse(status=200, data={'message': "OK",
                                                          'mod_time': snippet.modified_str})
                else:
                    return JsonResponse(status=401, data={'message': "Wrong POST data"})
            except Snippet.DoesNotExist:
                return JsonResponse(status=404, data={'message': "Snippet not found"})
        else:
            return create(request)
    else:
        return JsonResponse(status=400, data={'message': "Use POST"})


# /snippetalk/delete/<id>/
def delete(request, snippet_id):
    snippet = get_object_or_404(Snippet, id=snippet_id)
    snippet.delete()
    return HttpResponseRedirect(reverse('snippetalk:recent'))


# /snippetalk/comment/
def comment(request):
    if request.method == 'POST':
        try:
            print(json.loads(request.POST['snippets']))
            snippet = Snippet.objects.get(id=int(request.POST['id']))
            parent = Comment.objects.get(id=int(request.POST['parent'])) if request.POST['parent'] else None
            comm = Comment()
            comm.text = wrap_links(request.POST['comment'])
            comm.author = request.user if request.user.is_authenticated() else None
            comm.to_snippet = snippet
            comm.parent = parent
            comm.save()
            for s_id in json.loads(request.POST['snippets']):
                m_snippet = Snippet.objects.get(id=int(s_id))
                comm.snippets.add(m_snippet)
                m_snippet.save()
            comm.save()
            return JsonResponse(status=200,
                                data={
                                    'parent_id': comm.parent.id if comm.parent else 0,
                                    'html': comm.render(),
                                    'comment_count': snippet.comments.count()
                                })
        except Snippet.DoesNotExist:
            return JsonResponse(status=404, data={'message': "Snippet not found"})
    else:
        return JsonResponse(status=400, data={'message': "Use POST"})


# /snippetalk/download/<id>/
def download(request, snippet_id):
    snippet = get_object_or_404(Snippet, id=snippet_id)
    filename = snippet.get_file()
    file = open(filename)
    response = HttpResponse(file)
    file.close()
    os.remove(filename)
    response['Content-Disposition'] = 'attachment; filename="{0}"'.format(filename)
    return response


# /snippetalk/upload/
def upload(request):
    if request.method == 'POST':
        form = FileForm(request.POST, request.FILES)
        if form.is_valid():
            snippet = Snippet()
            name, lang_code = parse_filename(request.FILES['file'].name)
            code = request.FILES['file'].read().decode()
            snippet.language = lang_code
            highlighted = highlight(code, snippet.get_language_display())

            return JsonResponse(status=200, data={
                'message': "ok",
                'name': name,
                'lang_code': lang_code,
                # 'lang_name': snippet.get_language_display(),
                'raw': code,
                'highlighted': highlighted
            })
        else:
            return JsonResponse(status=400, data={'message': "Bad data"})
    else:
        return JsonResponse(status=400, data={'message': "Use POST"})


# /snippetalk/preview/
def preview(request):
    if request.method == 'GET':
        try:
            if not request.GET['id']:
                return JsonResponse(status=400, data={'message': "Missing parameter"})
            snippet = Snippet.objects.get(id=request.GET['id'])
            return JsonResponse(status=200, data={'code': snippet.highlighted})
        except Snippet.DoesNotExist:
            return JsonResponse(status=404, data={'message': "Snippet not found"})
    else:
        return JsonResponse(status=400, data={'message': "Use GET"})

django_project/snippetalk/templates/snippetalk/comment.html
<div class="list-group-item" data-id="{{ comm.id }}" xmlns="http://www.w3.org/1999/html">
  <div class="row">
    <div class="col-xs-1 col-sm-1 col-md-1 col-lg-1">
      {% if comm.author %}
        <a href="{% url 'profile' comm.author.username %}" class="thumbnail">
          <img src="{{ comm.author.userprofile.profile_image.url|default:"/media/images/default.jpg" }}"
               alt="image not found">
        </a>
      {% else %}
        <a class="thumbnail">
          <img src="/media/images/default.jpg" alt="image not found">
        </a>
      {% endif %}
      <div class="row comm">
        <button class="btn btn-xs btn-default btn-comm expand" data-toggle="tooltip" data-placement="bottom"
                title="Collapse" data-target="#answers-{{ comm.id }}">
            <span class="glyphicon glyphicon-chevron-down" ></span>
          </button>
      <button class="btn btn-xs btn-success btn-comm answer" data-toggle="tooltip" data-id="{{ comm.id }}"
              data-placement="bottom" title="Answer">
          <span class="glyphicon glyphicon-share-alt"></span>
      </button>
      </div>
    </div>
    <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10">
      <h4 class="list-group-item-heading">
        <small>
          <b>{{ comm.author.username|default:"Anonymous" }}</b> - {{ comm.created }}
        </small>
      </h4>
      <p>
        {{ comm.text|safe }}
      </p>
      {% if comm.snippets.all %}
        <small><i>Linked snippets:
        {% for snippet in comm.snippets.all %}
          {% if not forloop.last %}
             <a href="#">&gt;&gt;{{ snippet.name }},</a>
          {% else %}
             <a href="#">&gt;&gt;{{ snippet.name }}</a>
          {% endif %}
        {% endfor %}
      {% endif %}
    </i></small>
    </div>
  </div>
</div>
{#{% if comm.answers.all %}#}
  <div class="list-group collapse in" style="margin-left: 30px" id="answers-{{ comm.id }}">
    {% for answer in comm.answers.all %}
      {{ answer.render }}
    {% endfor %}
  </div>
{#{% endif %}#}

django_project/snippetalk/templates/snippetalk/create.html
{% extends "snippetalk/snippetalk.html" %}
{% load crispy_forms_tags %}

{% block title %}
    Create snippet.
{% endblock %}

{% block content %}
    <div class="container">
    	<form action="#" method="post" role="form">
        {% csrf_token %}
    	<legend>Create new snippet</legend>
        {{ form|crispy }}
    	<button type="submit" class="btn btn-default btn-block">Create</button>
    </form>
    </div>

{% endblock %}

django_project/snippetalk/templates/snippetalk/list.html
{% extends 'snippetalk/snippetalk.html' %}

{% block title %}
    recent snippets.
{% endblock %}

{% block content %}
    <div class="page-header">
        <h2>{{ title }}</h2>
    </div>
            <div class="list-group">

    {% for snippet in snippets %}
        <a href="{% url 'snippetalk:snippet' snippet.id %}" class="list-group-item">
            <h5 class="list-group-item-heading">
                {{ snippet.name }}<br>
                <small>
                    author: {{ snippet.author|default:"Anonymous" }}, created:
                  {{ snippet.created }},
                  modified:
                  {{ snippet.modified }},
                    language: {{ snippet.get_language_display }}
                </small>
            </h5>
            <p class="list-group-item-text">{{ snippet.description }}</p>
        </a>
    {% empty %}
        <a href="{% url 'snippetalk:create' %}" class="list-group-item">
            <h4 class="list-group-item-heading">
                There is no snippets now.
            </h4>
            <p class="list-group-item-text">You can create first one.</p>
        </a>
    {% endfor %}
    </div>

{% endblock %}

django_project/snippetalk/templates/snippetalk/snippet.html
{% extends "snippetalk/snippetalk.html" %}
{% load staticfiles %}

{% block title %}
  {{ title }}
{% endblock %}

{% block headers %}
  <link href="{% static "bootstrap3-editable/css/bootstrap-editable.css" %}" rel="stylesheet"
        type="text/css">
  <link href="{% static "select2/css/select2.min.css" %}" rel="stylesheet" type="text/css">
  <link href="{% static "select2/css/select2-bootstrap.min.css" %}" rel="stylesheet"
        type="text/css">
  <link href="{% static "ladda-bootstrap/css/ladda-themeless.min.css" %}" rel="stylesheet" type="text/css">
  <link href="{% static "snippetalk/css/highlight.css" %}" rel="stylesheet" type="text/css">
  <link href="{% static "snippetalk/css/snippetalk.css" %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}
  {% csrf_token %}


  <div class="modal fade" id="existing-modal">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Select snippet</h4>
        </div>
        <div class="modal-body">
          <select name="snippet-select" id="snippet-select">
            {% for snippet in my_snippets %}
              <option value="{{ snippet.id }}">{{ snippet.name }}</option>
            {% endfor %}
          </select>
          <div class="panel panel-default panel-code">
            <div class="panel-body">
              <div class="highlight" id="my-snippet">
                <ol>
                  {{ my_snippets.0.highlighted | safe }}
                </ol>
              </div>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <div class="btn-group" role="group">
            <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
            <button type="button" class="btn btn-success" id="add-snippet" data-dismiss="modal">Add to comment</button>
          </div>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->

  <div class="page-header">
    <h2>
      <a href="#" id="name" data-type="text" data-pk="{{ snippet.id }}"
        >{{ snippet.name | default:"Untitled"}}</a><br>
      <small>
        {% if snippet %}
          by
          {% if snippet.author %}
            <a href="{% url 'profile' snippet.author.username %}">{{ snippet.author.username }}</a>
          {% else %}
            Anonymous
          {% endif %}
          <br>
        {% endif %}

        <small>
          {% if snippet.created %}
            created: {{ snippet.created }},
          {% endif %}
          {% if snippet.modified %}
            modified: <span id="modified">{{ snippet.modified }}</span>
          {% endif %}
          language: <a href="#" id="lang" data-type="select2"
                       data-value="{{ snippet.language|default:plain_text }}"
                       data-inputclass="ccc">
          {{ snippet.get_language_display|default:"Text only" }}</a>,
          privacy: <a href="#" id="public" data-type="select2"
                      data-value="{{ snippet.public|default:1 }}">
          {{ snippet.get_public_display|default:"Public" }}</a>
        </small>
      </small>
    </h2>
  </div>
  <div class="panel panel-default panel-code">
    <div class="panel-body">
      {# #######################TOOLBAR################################ #}
      <div class="row tools">
        <ul class="nav navbar-nav nav-pils navbar-right" id="snippet-buttons">
          {% if not snippet %}
            <form enctype="multipart/form-data" method="post" name="fileform">
              {% csrf_token %}
              <input type="file" id="file" name="file" class="hidden">
            </form>
            <li role="presentation">
              <button class="btn" data-toggle="tooltip" data-placement="bottom" title="Upload" id="upload">
                <span class="glyphicon glyphicon-open" aria-hidden="true"></span>
              </button>
            </li>
          {% endif %}
          {% if snippet.id %}
            <li role="presentation">
              <button onclick="location.href='{% url 'snippetalk:download' snippet.id %}'" class="btn btn-xs" data-toggle="tooltip"
                 data-placement="bottom" title="Download">
                <span class="glyphicon glyphicon-save" aria-hidden="true"></span>
              </button>
            </li>
            <li role="presentation">
              <button onclick="location.href='{% url 'snippetalk:fork' snippet.id %}'" class="btn btn-xs" data-toggle="tooltip"
                 data-placement="bottom"
                 title="Fork">
                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
              </button>
            </li>
          {% endif %}
          {% if mine %}
            <li role="presentation">
              <button class="btn btn-xs" id="save" data-toggle="tooltip" data-placement="bottom"
                 title="Save">
                <span class="glyphicon glyphicon-floppy-disk" aria-hidden="true"></span>
              </button>
            </li>
            {% if snippet.id %}
              <li role="presentation">
                <button onclick="location.href='{% url 'snippetalk:delete' snippet.id %}'" class="btn btn-xs" id="delete"
                   data-toggle="tooltip" data-placement="bottom" title="Delete">
                  <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                </button>
              </li>
            {% endif %}
          {% endif %}
        </ul>
        <ul class="nav nav-tabs" id="code-tabs" role="tablist">
          <li role="presentation" class="active" id="highlight_tab">
            <a href="#highlight" aria-controls="highlight" role="tab" data-toggle="tab">Snippet</a>
          </li>
          <li role="presentation" id="raw_tab">
            <a href="#raw" aria-controls="raw" role="tab" data-toggle="tab">Raw</a>
          </li>
          <li role="presentation" id="desc_tab">
            <a href="#desc" aria-controls="desc" role="tab" data-toggle="tab">Description</a></li>
        </ul>
      </div>
      {#  ###################TOOLBAR END############################  #}
      <div class="tab-content">
        <div class="highlight tab-pane fade in active" id="highlight" role="tabpanel">
          <ol>{{ snippet.highlighted | safe }}</ol>
          <div class="shadow" style="display: none" id="code-shadow"></div>
        </div>
        <div id="raw" class="tab-pane fade" role="tabpanel">
          <form>
                <textarea class="form-control" id="raw-ta" {% if not mine %}readonly
                {% endif %}>{{ snippet.code }}</textarea>
          </form>
        </div>
        <div id="desc" class="tab-pane fade" role="tabpanel">
          <form>
            <textarea class="form-control" id="desc-ta" {% if not mine %}readonly{% endif %}
              >{{ snippet.description }}</textarea>
          </form>
        </div>
      </div>
    </div>
  </div>
  {#  Snippet ends  #}
  {#  Comment Area  #}
  {% if snippet.id %}
    <div class="page-header">
      <h3>
        Comments(<span id="comment-count">{{ snippet.comments.count }}</span>)
          <button class="btn btn-default round expand no-transition" data-toggle="tooltip" data-placement="bottom" title="Collapse"
            data-target=".comments.all" data-animation="false">
            <span class="glyphicon glyphicon-chevron-down" aria-hidden="true"></span>
          </button>

        <button class="btn btn-success round" data-toggle="tooltip" data-placement="bottom" title="Add Comment"
          id="comment" data-id>
          <span class="glyphicon glyphicon-share-alt" ></span>
        </button>
      </h3>

    </div>


    <div class="list-group comments all collapse in" id="answers-0">
      {% for comment in snippet.top_level_comments %}
        {{ comment.render }}
      {% endfor %}
    </div>
  {% endif %}
  {#  End of Comment Area  #}
  <textarea id="raw-ta-hidden" class="hidden">{{ snippet.code }}</textarea>
  <input type="text" id="snippet-id" class="hidden" value="{{ snippet.id|default_if_none:'' }}"/>
{% endblock %}

{% block scripts %}
  <script src="{% static "bootstrap3-editable/js/bootstrap-editable.min.js" %}"></script>
  <script src="{% static "select2/js/select2.full.js" %}"></script>
  <script src="{% static "snippetalk/js/snippetalk.js" %}"></script>
  <script src="{% static "ladda-bootstrap/js/spin.min.js" %}"></script>
  <script src="{% static "ladda-bootstrap/js/ladda.min.js" %}"></script>
  <script>
    mine = {{ mine | lower}};
    data_source = {{ langs | safe }};
  </script>
{% endblock %}

django_project/snippetalk/templates/snippetalk/snippetalk.html
{% extends "base.html" %}

{% block title-project %}
    SnippeTalk
{% endblock %}

{% block project %} SnippeTalk {% endblock %}

{% block project_navbar %}
    <li class="divider-vertical"></li>
    <li {% if active_page == 'recent' %}class="active"{% endif %}>
        <a href="{% url 'snippetalk:recent' %}">Recent snippets</a>
    </li>
    <li {% if active_page == 'my' %}class="active"{% endif %}>
        <a href="{% url 'snippetalk:my' %}">My snippets</a>
    </li>

{% endblock %}

{% block project_navbar_right %}
    <li {% if active_page == 'create' %}class="active"{% endif %}>
        <a href="{% url 'snippetalk:create' %}">Create snippet</a>
    </li>
    <li class="divider-vertical"></li>
{% endblock %}