django_project/chat/urls.py
from django.conf.urls import patterns, url

__author__ = 'nonameitem'

urlpatterns = patterns('',
                       url(r'^$', 'chat.views.show_chat_list', name='main'),
                       url(r'^new/$', 'chat.views.create_chat', name='new'),
                       url(r'^(?P<chat_id>\d+)/$', 'chat.views.show_chat', name='chat'),
                       url(r'^post/(?P<chat_id>\d+)/$', 'chat.views.post', name='post'),
                       url(r'^add_user/(?P<chat_id>\d+)/$', 'chat.views.add_user', name='add_user'),
                       url(r'^add_users/(?P<chat_id>\d+)/$', 'chat.views.add_users', name='add_users'),
                       url(r'^leave/(?P<chat_id>\d+)/$', 'chat.views.leave', name='leave'),
                       url(r'^change_topic/', 'chat.views.change_topic', name='change_topic'),
                       url(r'^get_previous/(?P<chat_id>\d+)/$', 'chat.views.get_previous', name='previous'),
                       url(r'^get_updates/(?P<chat_id>\d+)/$', 'chat.views.get_updates', name='updates'),
                       url(r'^merge_private/(?P<user_id>\d+)/$', 'chat.views.merge_private', name='merge_private'),
                       )

django_project/django_project/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
import django_project.settings as settings
import django_project.views as views

urlpatterns = patterns('',
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^accounts/register/$', views.MyRegistrationView.as_view(), name='registration_register'),
                       url(r'^accounts/profile/$', 'django_project.views.my_profile', name='my_profile'),

                       url(r'^accounts/', include('registration.backends.simple.urls')),
                       url(r'^chat/', include('chat.urls', namespace='chat')),
                       url(r'^snippetalk/', include('snippetalk.urls', namespace='snippetalk')),
                       url(r'^ca/', include('cell_auto.urls', namespace='ca')),
                       url(r'^bot/', include('bots_common.urls')),

                       url(r'^$', 'django_project.views.home', name='home'),
                       url(r'^user/(?P<username>\w+)/$', views.profile, name='profile'),
                       url(r'^change_photo/(?P<user_id>\d+)/$', views.change_photo, name='change_photo'),
                       url(r'^change_profile/(?P<user_id>\d+)/$', views.change_profile, name='change_profile'),
                       )

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_project/snippetalk/urls.py
from django.conf.urls import patterns, url

__author__ = 'nonameitem'

urlpatterns = patterns('',
                       url(r'^$', 'snippetalk.views.recent', name='recent'),
                       url(r'^my/$', 'snippetalk.views.my', name='my'),
                       url(r'^create/$', 'snippetalk.views.show', name='create'),
                       url(r'^(?P<snippet_id>\d+)/$', 'snippetalk.views.show', name='snippet'),
                       url(r'^highlight/$', 'snippetalk.views.get_highlight', name='get_highlight'),
                       url(r'^save/$', 'snippetalk.views.save', name='save'),
                       url(r'^delete/(?P<snippet_id>\d+)/$', 'snippetalk.views.delete', name='delete'),
                       url(r'^fork/(?P<snippet_id>\d+)/$', 'snippetalk.views.show', {'fork': True}, name='fork'),
                       url(r'^comment/$', 'snippetalk.views.comment', name='comment'),
                       url(r'^download/(?P<snippet_id>\d+)/$', 'snippetalk.views.download', name='download'),
                       url(r'^upload/$', 'snippetalk.views.upload', name='upload'),
                       url(r'^preview/$', 'snippetalk.views.preview', name='preview'),
                       )

django_project/chat/models.py
import json
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.template.loader import render_to_string


class Chat(models.Model):
    name = models.CharField(max_length=255, unique=False, blank=False)
    topic = models.CharField(max_length=255, unique=False, blank=True)
    participants = models.ManyToManyField(User)
    last_message_time = models.DateTimeField(null=True, blank=True, db_index=True)
    last_message_sender = models.ForeignKey(User, null=True, related_name='last_sender')

    def __str__(self):
        return self.name

    def get_user_list(self):
        return self.participants.all().order_by('username')

    def get_choice(self):
        return self.id, "{0} ({1})".format(self.name, self.topic)

    @property
    def last_message(self):
        if self.message_set.count() > 0:
            return self.message_set.order_by('-datetime')[0].text
        else:
            return ''


class Message(models.Model):
    text = models.TextField()
    sender = models.ForeignKey(User)
    thread = models.ForeignKey(Chat)
    datetime = models.DateTimeField(auto_now_add=True, db_index=True)

    def get_json_string(self):
        if self.sender.userprofile.profile_image:
            photo_url = self.sender.userprofile.profile_image.url
        else:
            photo_url = "/media/images/default.jpg"
        return json.dumps({
            'type': 'M',
            'username': self.sender.username,
            'photo': photo_url,
            'message': self.text
        })

    def __str__(self):
        return "[Chat #{0.thread.id}] {0.sender.username}: {0.text}".format(self)


def update_last_message(message):
    Chat.objects.filter(id=message.thread.id).update(
        last_message_time=message.datetime, last_message_sender=message.sender)

django_project/chat/forms.py
from django import forms
from chat.models import Chat
from chat.utils import get_private_chats

__author__ = 'nonameitem'


class ChatForm(forms.ModelForm):

    class Meta:
        model = Chat
        fields = ('name', 'topic', 'participants')
        widgets = {
            'participants': forms.SelectMultiple(attrs={'title': 'Select users'})
        }


class PrivateChatForm(forms.ModelForm):

    class Meta:
        model = Chat
        fields = ('name', 'topic')


def get_merge_form(user, other):
    chats = get_private_chats(user, other)
    choices = []
    for ch in chats:
        choices.append(ch.get_choice())

    class MergePrivateChatsForm(forms.Form):
        new_title = forms.CharField(max_length=255, initial="{0} <--> {1}".format(user.username, other.username))
        new_topic = forms.CharField(max_length=255, required=False)
        chats = forms.TypedMultipleChoiceField(coerce=lambda x: Chat.objects.get(id=x), choices=choices)

        def clean_chats(self):
            clean_data = self.cleaned_data['chats']
            if len(clean_data) < 2:
                raise forms.ValidationError('Please, select at least 2 chats')
            return clean_data

    return MergePrivateChatsForm

django_project/chat/views.py
import json
import datetime
import re

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseRedirect, JsonResponse, Http404, HttpResponse
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from django.core.urlresolvers import reverse
import pika

from chat.models import Chat, Message, update_last_message
from chat.forms import ChatForm, get_merge_form


# url regex from http://daringfireball.net/2010/07/improved_regex_for_matching_urls
URL_REGEX = re.compile(r'''(?i)\b((?:[a-z][\w-]+:(?:/{1,3}|[a-z0-9%])|www\d{0,3}[.]|[a-z0-9.\-]+[.][a-z]{2,4}/)(?:[^\s\
()<>]+|\(([^\s()<>]+|(\([^\s()<>]+\)))*\))+(?:\(([^\s()<>]+|(\([^\s()<>]+\)))*\)|[^\s`!()\[\]{};:'".,<>?«»“”‘’]))''')


def wrap_links(text):
    return URL_REGEX.sub(lambda x: '<a href="{0}">{0}</a>'.format(x.group(0)), text)


@login_required
def show_chat_list(request):
    chats = Chat.objects.filter(participants=request.user).order_by('-last_message_time')
    return render_to_response('chat/chat_list.html',
                              {'chats': chats,
                               'active_page': 'all'},
                              RequestContext(request))


@login_required
def create_chat(request):
    if request.method == 'POST':
        form = ChatForm(request.POST)
        if form.is_valid():
            chat = form.save()
            if request.user not in chat.participants.all():
                chat.participants.add(request.user)
            mess = {
                'id': chat.id,
                'name': chat.name,
                'text': chat.topic,
                'sender': request.user.username,
                'link': reverse('chat:chat', kwargs={'chat_id': chat.id})
            }
            for user in chat.get_user_list():
                post_to_notify_queue(str(user.id), json.dumps({
                    'type': "C",
                    'mess': mess
                }))
            return HttpResponseRedirect(reverse('chat:chat', kwargs={'chat_id': chat.id}))
    else:
        form = ChatForm()
    return render_to_response('chat/create_chat.html',
                              {'form': form,
                               'active_page': 'create'},
                              RequestContext(request))


@login_required
def show_chat(request, chat_id):
    message_blocks = None
    not_all = False
    oldest_datetime = datetime.datetime.now()
    chat = get_object_or_404(Chat, id=chat_id)
    if request.user not in chat.participants.all():
        raise PermissionDenied
    participants = chat.participants.all()
    potential_participants = User.objects.exclude(id__in=participants.distinct())

    messages = chat.message_set.all().order_by('-datetime')[:100]
    if messages.count() > 0:
        first_message = chat.message_set.order_by('datetime')[0]
        not_all, oldest_datetime, message_blocks = make_message_blocks(first_message, messages)

    return render_to_response('chat/show_chat.html',
                              {'chat': chat,
                               'message_blocks': message_blocks,
                               'potential_participants': potential_participants.order_by('username'),
                               'not_all': not_all,
                               'oldest_datetime': oldest_datetime.timestamp(),
                               'newest_datetime': datetime.datetime.now().timestamp()},
                              RequestContext(request))


def make_message_blocks(first_message, messages):
    message_blocks = []
    not_all = False
    oldest_datetime = None

    if messages.count() > 0:
        message_block = dict({'sender': messages[0].sender.username,
                              'photo': messages[0].sender.userprofile.image_url,
                              'messages': []})
        oldest_message = messages[messages.count() - 1]
        not_all = oldest_message != first_message
        oldest_datetime = oldest_message.datetime
        for message in messages:
            if message.sender.username == message_block['sender']:
                message_block['messages'].insert(0, message.text)
            else:
                message_blocks.insert(0, message_block)
                message_block = {'sender': message.sender.username,
                                 'photo': message.sender.userprofile.image_url,
                                 'messages': [message.text]}
        message_blocks.insert(0, message_block)
    return not_all, oldest_datetime, message_blocks


@login_required
def post(request, chat_id):
    if request.method == 'POST':
        chat = get_object_or_404(Chat, id=chat_id)

        if request.user not in chat.participants.all():
            raise PermissionDenied

        message = Message()
        message.text = wrap_links(request.POST['message'])
        message.sender = request.user
        message.thread = chat
        message.save()
        update_last_message(message)

        post_to_chat_queue(chat_id, message.get_json_string())
        mess = {
            'id': chat.id,
            'name': chat.name,
            'text': message.text,
            'sender': request.user.username,
            'link': reverse('chat:chat', kwargs={'chat_id': chat.id})
        }
        for user in chat.participants.all():
            post_to_notify_queue(str(user.id), json.dumps({
                'type': 'M',
                'mess': mess
            }))

        return JsonResponse(status=200, data={'result': True})

    else:
        return JsonResponse(status=400, data={'result': False})


# TODO: Refactor to one function
def post_to_chat_queue(chat_id, message):
    conn = pika.BlockingConnection(pika.ConnectionParameters('127.0.0.1'))
    channel = conn.channel()
    channel.exchange_declare(exchange='chat',
                             type='direct')
    channel.basic_publish(exchange='chat',
                          routing_key=chat_id,
                          body=message.encode('utf8'))


def post_to_notify_queue(user_id, message):
    conn = pika.BlockingConnection(pika.ConnectionParameters('127.0.0.1'))
    channel = conn.channel()
    channel.exchange_declare(exchange='notify',
                             type='direct')
    channel.basic_publish(exchange='notify',
                          routing_key=user_id,
                          body=message.encode('utf8'))


@login_required
def add_users(request, chat_id):
    if request.method == 'POST':
        chat = get_object_or_404(Chat, id=chat_id)
        if request.user not in chat.participants.all():
            raise PermissionDenied

        ids = json.loads(request.POST['selected'])
        for user_id in ids:
            user = get_object_or_404(User, id=user_id)
            chat.participants.add(user)
            mess = {
                'id': chat.id,
                'name': chat.name,
                'text': None,
                'sender': request.user.username,
                'link': reverse('chat:chat', kwargs={'chat_id': chat.id})
            }
            post_to_notify_queue(str(user.id), json.dumps({
                'type': 'I',
                'mess': mess
            }))
        data = get_user_lists(chat)
        post_to_chat_queue(chat_id, json.dumps(data))

        return JsonResponse(status=200, data={'message': "OK"})
    else:
        return JsonResponse(status=400, data={'message': "Please use POST"})


def get_user_lists(chat):
    participants = chat.participants.all()
    potential_participants = User.objects.exclude(id__in=participants.distinct())
    participants_out = []
    for participant in participants:
        participants_out.append(participant.username)
    participants_out.sort()
    potential_participants_out = []
    for participant in potential_participants:
        potential_participants_out.append((participant.id, participant.username))
    potential_participants_out.sort(key=lambda x: x[1])
    data = {'type': 'U',
            'participants': participants_out,
            'potential_participants': potential_participants_out}
    print(json.dumps(data))
    return data


@login_required
def leave(request, chat_id):
    chat = get_object_or_404(Chat, id=chat_id)
    if request.user not in chat.participants.all():
        raise PermissionDenied
    chat.participants.remove(request.user)
    if len(chat.participants.all()) > 0:
        data = get_user_lists(chat)
        post_to_chat_queue(chat_id, json.dumps(data))
    else:
        chat.delete()
    return HttpResponseRedirect(reverse('chat:main'))


@login_required
def change_topic(request):
    if request.method == 'POST':
        try:
            chat = Chat.objects.get(id=request.POST['pk'])
        except Chat.DoesNotExist:
            return HttpResponse("Chat not found", status=404)
        if request.user not in chat.participants.all():
            raise PermissionDenied
        chat.topic = request.POST['value']
        chat.save()
        data = {'type': 'T',
                'topic': chat.topic}
        post_to_chat_queue(str(chat.id), json.dumps(data))
        mess = {
            'id': chat.id,
            'name': chat.name,
            'text': chat.topic,
            'sender': request.user.username,
            'link': reverse('chat:chat', kwargs={'chat_id': chat.id})
        }
        for user in chat.get_user_list():
            post_to_notify_queue(str(user.id), json.dumps({
                'type': "T",
                'mess': mess
            }))
        return HttpResponse(status=200)
    else:
        return HttpResponse("Bad request", status=400)


@login_required
def get_previous(request, chat_id):
    chat = get_object_or_404(Chat, id=chat_id)
    if request.user not in chat.participants.all():
        raise PermissionDenied

    if request.method == 'GET':

django_project/chat/templates/chat/chat.html
{% extends "base.html" %}

{% block title-project %}
  Chat
{% endblock %}

{% block project %} Chat {% endblock %}

{% block project_navbar %}
  <li class="divider-vertical"></li>
  {% if user.is_authenticated and recent_chats %}
    <li {% if active_page == 'all' %}class="active"{% endif %}>
    <a href="{% url 'chat:main' %}">All</a>
  </li>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
         aria-expanded="false">Recent <span class="caret"></span></a>
      <ul class="dropdown-menu">
        {% for chat in recent_chats %}
          <li><a href="{% url 'chat:chat' chat.id %}">{{ chat.name }}</a></li>
        {% endfor %}
      </ul>
    </li>
  {% endif %}
{% endblock %}

{% block project_navbar_right %}
  <li {% if active_page == 'create' %}class="active"{% endif %}>
    <a href="{% url 'chat:new' %}">Start chat</a>
  </li>
  <li class="divider-vertical"></li>
{% endblock %}

django_project/chat/templates/chat/chat_list.html
{% extends "chat/chat.html" %}

{% block title %}
    chat list
{% endblock %}

{% block content %}
    <div class="page-header">
      <h2>Chat list<small><br>Select chat or create a new one</small></h2>
    </div>
{#    <div class="jumbotron">#}
    	<div class="list-group">
      {% for chat in chats %}
        <a href="{% url 'chat:chat' chat.id %}" class="list-group-item">
            <h5 class="list-group-item-heading">
                {{ chat.name }}
              <small>{{ chat.topic }}</small>
            </h5>
            <p class="list-group-item-text"><i>
              {% if chat.last_message %}
              [{{ chat.last_message_time }}]{{ chat.last_message_sender }}: {{ chat.last_message }}
              {% else %}
                No messages yet
              {% endif %}

            </i></p>
        </a>
    {% empty %}
        <a href="{% url 'snippetalk:create' %}" class="list-group-item">
            <h4 class="list-group-item-heading">
                There is no chats now.
            </h4>
            <p class="list-group-item-text">You can create first one.</p>
        </a>
    {% endfor %}



    	</div>
  <a class="btn btn-default btn-block" href="/chat/new/">Create new chat</a>
{#    </div>#}
{% endblock %}

django_project/chat/templates/chat/create_chat.html
{% extends "chat/chat.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block title %}
    start new chat
{% endblock %}

{% block headers %}
    <link href="{% static "bootstrap-select/css/bootstrap-select.min.css" %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}

    <form action="#" method="post" role="form">
        {% csrf_token %}
        <legend>Create new chat</legend>
        {{ form|crispy }}

        <button type="submit" class="btn btn-default btn-block">Create</button>
    </form>


{% endblock %}

{% block scripts %}
{#  <script src="{% static "bootstrap-select/js/bootstrap-select.min.js" %}"></script>#}
{##}
{#  <script>$('.selectpicker').selectpicker();$('.bootstrap-select .dropdown-menu').removeClass('open');</script>#}
  <script src="{% static "select2/js/select2.min.js" %}"></script>
  <script >
    $('select').select2();
  </script>
{% endblock %}

django_project/chat/templates/chat/merge_private.html
{% extends "chat/chat.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block title %}
    start new chat
{% endblock %}

{% block headers %}
    <link href="{% static "bootstrap-select/css/bootstrap-select.min.css" %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}
    <form action="#" method="post" role="form">
        {% csrf_token %}
    	<legend>Merge private chats with {{ other }}</legend>
        {{ form|crispy }}

    	<button type="submit" class="btn btn-default btn-block">Create</button>
    </form>
{% endblock %}

{% block scripts %}
    <script src="{% static "bootstrap-select/js/bootstrap-select.min.js" %}"></script>
{% endblock %}

django_project/chat/templates/chat/show_chat.html
{% extends "chat/chat.html" %}
{% load staticfiles %}

{% block title %}
  {{ chat.name }}
{% endblock %}

{% block headers %}
  <link href="{% static "bootstrap-select/css/bootstrap-select.min.css" %}" rel="stylesheet" type="text/css">
  <link href="{% static "bootstrap3-editable/css/bootstrap-editable.css" %}" rel="stylesheet" type="text/css">
  <link href="{% static "ladda-bootstrap/css/ladda-themeless.min.css" %}" rel="stylesheet"  type="text/css">
  <link href="{% static "chat/css/chat_page.css" %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}
  <div class="page-header">
    <h2>
      {{ chat.name }}
      <small>
        <a href="#" id="topic" data-type="text" data-pk="{{ chat.id }}" data-title="Change topic" data-url="/chat/change_topic/">
          {{ chat.topic|default:"set topic" }}
        </a>
      </small>
    </h2>
  </div>
  <div class="row">
    <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8 main-col">
      <div class="well well-lg main">
        {% if not_all %}
          <button class="btn btn-block btn-lg ladda-button load-more" data-oldest="{{ oldest_datetime }}"
                  data-style="slide-up" data-size="l">
            <span class="ladda-label">Load more</span>
          </button>
        {% endif %}
        {% for message_block in message_blocks %}
          <div class="row message_block">
            <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2" align="right">
              <a href="{% url 'profile' message_block.sender %}" target="_blank" class="thumbnail">
                <img src="{{ message_block.photo }}" alt="Image">
              </a>
            </div>
            <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10">
              <div class="alert {% if message_block.sender == user.username %}alert-success{% else %}alert-info{% endif %}">
                <a href="{% url 'profile' message_block.sender %}" target="_blank" class="sender"><strong>{{ message_block.sender }}</strong></a>
                {% for message in message_block.messages %}
                  <div>{{ message|safe }}</div>
                {% endfor %}
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
      <div class="input-group input-group-lg">
        <input type="text" class="form-control message" name="message" id="id_message" placeholder="Message">
          <span class="input-group-btn">
            <button class="btn btn-default send-button" type="button">Send</button>
          </span>
      </div>
    </div>
    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Users</h3>
        </div>
        <div class="panel-body">
          <ul id="id_userlist">
            {% for chat_user in chat.get_user_list %}
              <li><p><a target="_blank" href="{% url 'profile' chat_user.username %}">{{ chat_user.username }}</a></p></li>
            {% endfor %}
          </ul>
          <div class="userlist-control">
            <p><button type="button" class="btn btn-default btn-block" id="add_user_button">Add user(s) to chat</button></p>
            <p><form action="#" method="post"  role="form" id="add_user_form">
            {% csrf_token %}
            <div class="form-group">
              <select multiple="multiple" id="id_participants" name="participants" title="Select users">
                {% for potential_participant in potential_participants %}
                  <option value="{{ potential_participant.id }}">{{ potential_participant.username }}</option>
                {% empty %}
                  <option disabled="disabled">All users are already here)</option>
                {% endfor %}

              </select>
            </div>
            <button type="submit" class="btn btn-default">Add</button>
            <button type="button" class="btn btn-danger" id="cancel_add_user">Cancel</button>
          </form></p>
            <p><a href="/chat/leave/{{ chat.id }}" class="btn btn-danger btn-block">Leave chat</a></p>
          </div>

        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block scripts %}
  <script src="{% static "bootstrap3-editable/js/bootstrap-editable.min.js" %}"></script>
  <script src="{% static "ladda-bootstrap/js/spin.min.js" %}"></script>
  <script src="{% static "ladda-bootstrap/js/ladda.min.js" %}"></script>
  <script src="{% static "chat/js/chat_page.js" %}"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-visibility/1.0.11/jquery-visibility.js"></script>
  <script src="{% static "select2/js/select2.min.js" %}"></script>
  <script type="text/javascript">
    $(document).ready(function(){

      {% if oldest_datetime %}
        oldest = "{{ oldest_datetime }}";
      {% endif %}
      newest = '{{ newest_datetime }}';
      startChat({{ chat.id }}, '{{ user.username }}');
      currChatId = {{ chat.id }};
      $('select').select2({width: '100%'});
    });
  scrollDown();
  </script>
{% endblock %}